parameters:
    job_name: ''
    image_name: ''
    python_versions: []
    test_suites: {}
    python_architecture: x64

jobs:
    - job: ${{ parameters.job_name }}

      pool:
          vmImage: ${{ parameters.image_name }}

      strategy:
          matrix:
              ${{ each tsuite in parameters.test_suites }}:
                 ${{ tsuite.key }}:
                     test_suite_label: ${{ tsuite.key }}
                     test_suite: ${{ tsuite.value }}

      steps:
          - checkout: self
            fetchDepth: 10

          - task: Docker@2
            inputs:
                command: 'build'
                Dockerfile: '**/Dockerfile'
                arguments: '-t scancode'
            displayName: 'Build scancode-toolkit container'

          - script: |
              docker run scancode --help
